### ISSUE TITLE
Add Sounds

### ISSUE THREAD

**Issue by averyzheng-yay** [ewang25/hexa-gone#3]
Explore possible sound effects for clicking a tile, flagging a tile, revealing numbers, revealing a bomb, win/loss sounds, and potentially background music.

**Comment by averyzheng-yay** [comment]
Explore sounds: “import AVKit” at the top of whichever file the logic functions are implemented in, then use “AudioServicesPlaySystemSound(…)” (where … is the sound ID, e.g. 1005, see github.com/TUNER88/iOSSystemSoundsLibrary for complete list). If we have time, we can also add some background music (and perhaps a setting window to turn BGM and SFX on/off. - Darren

**Comment by npvq** [comment]
Since sounds are in working order, will close issue for now.
