### ISSUE TITLE
Remove Impossible Scenarios

### ISSUE THREAD

**Issue by averyzheng-yay** [ewang25/hexa-gone#6]
Self-explanatory; however, may be extremely hard to fix. Optional fix.

**Comment by npvq** [comment]
Impossible scenarios are part of the Minesweeper gameplay. We implemented "hints" as a simple workaround to forced guesses (but the player has to allocate the limited available hints throughout the game).

It is possible to implement a NG (No Guessing) mode, as seen on [minesweeper.online](https://minesweeper.online/), but for this project we probably won't need such a feature with hints already implemented.
